---
name: Renovate
on:
  workflow_call:
    inputs:
      dryRun:
        description: Dry-Run
        default: false
        required: false
        type: boolean
      logLevel:
        description: Log-Level
        default: debug
        required: false
        type: string
      autoDiscover:
        description: Enable Repo Auto Discovery
        default: false
        required: false
        type: boolean
      autoDiscoverFilter:
        description: Repo Auto Discover Filter
        default: "*"
        required: false
        type: string
      version:
        description: Renovate version
        default: latest
        required: false
        type: string
    secrets:
      app_id:
        description: App ID
        required: true
      app_private_key:
        description: App Private Key
        required: true

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_private_key }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Renovate
        uses: renovatebot/github-action@042670e39b8d7335e992c3fa526ecbfbd52ef57b # v40.2.2
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
          RENOVATE_DRY_RUN: ${{ inputs.dryRun || false }}
          RENOVATE_AUTODISCOVER: ${{ inputs.autoDiscover || 'false' }}
          RENOVATE_AUTODISCOVER_FILTER: ${{ inputs.autoDiscoverFilter || '*' }}
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
        with:
          token: ${{ steps.app-token.outputs.token }}
          renovate-version: ${{ inputs.version || 'latest' }}
